#!/bin/bash

# Copyright (c) 2018 David 'Mokon' Bond <mokon@mokon.net>
# Author: David 'Mokon' Bond <mokon@mokon.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

EnumFile=$1

EnumName="$(basename -s .enum $EnumFile)"
EnumDir="$(dirname $EnumFile)"
EnumSwitch=""
EnumCodes=""

while read -r line || [[ -n "$line" ]]; do
  if [[ ! -z "${line// }" ]] ; then
    code="${line// }"
    EnumCodes+="    $code,\n"
    EnumSwitch+="            case $EnumName::$code:\n                return \"$code\";\n"
  fi
done <<< "$(gsed -r ':a;$!{N;ba};s|/\*[^*]*\*+([^/*][^*]*\*+)*/||' ../../../$EnumFile)"
EnumCodes=${EnumCodes::${#EnumCodes}-2}
EnumSwitch=${EnumSwitch::${#EnumSwitch}-2}

mkdir -p $EnumDir
while IFS='' read -r line || [[ -n "$line" ]]; do
    while [[ "$line" =~ (\$\{[a-zA-Z_][a-zA-Z_0-9]*\}) ]] ; do
        LHS=${BASH_REMATCH[1]}
        RHS="$(eval echo "\"$LHS\"")"
        line="${line//$LHS/$RHS}"
    done
    echo -e "$line"
done < ../../../tools/codegen/templateEnum > $EnumDir/${EnumName}.hpp
