#!/bin/bash
# Copyright (c) 2018 David 'Mokon' Bond <mokon@mokon.net>
# Author: David 'Mokon' Bond <mokon@mokon.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

function failmsg {
  color red
  echo -ne "$1"
  color reset
}

function infomsg {
  color blue
  echo -ne "$1"
  color reset
}

function color {
  case $1 in
  black)
		echo -en "\033[0;30;10m" ;;
  yellow)
		echo -en "\033[0;33;10m" ;;
  purple)
		echo -en "\033[0;35;10m" ;;
  white)
		echo -en "\033[0;37;10m" ;;
  cyan)
		echo -en "\033[0;36;10m" ;;
  blue)
		echo -en "\033[0;34;10m" ;;
  red)
		echo -en "\033[0;31;10m" ;;
  green)
		echo -en "\033[0;32;10m" ;;
  reset|*)
		echo -en "\033[0;0m" ;;
  esac
}
